---
# All of this is optional and matches the defaults, but provided here to
# document what can be changed.

project:      resume
theme:        table-based

watch:        false
watchSleepMs: 500
errorSleepMs: 10000
throbber:     spinner

dataDir:      data

# By default these are derived from 'project'
projectDir:   data/projects
data:         data/projects/resume.coffee
destination:  public/resume.html

# And these are derived from 'theme'
themeDir:     data/themes/table-based
template:     data/themes/table-based/main.pug
